const strings = {
  EmailPlaceholder: 'E-mail address',
  PasswordPlaceholder: 'Password',
  envelopeIcon: 'envelope',
  lockIcon: 'lock',
  eyeIcon: 'eye',
  eyeSlashIcon: 'eye-slash',
  none: 'none',
  LOGIN: 'LOGIN',
  welcome: 'Welcome',
  findhome: 'Login for enjoy findhome',
  email: 'Email',
  password: 'Password',
  forgpass: 'Forgot password?',
  createnew: 'create new account',
  helloeddie: 'Hello Eddie!',
  startlookn: 'Start looking for your house',
  home: 'Home',
  specialhousemix: 'Special House mix',
  name: 'Timmy bremer',
  price: '$1500 usd',
  opinions: '20 opinions',
  number1: '1',
  number2: '2',
  location: 'Los Angeles, CA',
};

export default strings;
